### ISSUE TITLE
Merge bulk proposals?

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/conditional-segment-initialization#1]
Given the recent direction of the proposal, should we perhaps merge this with WebAssembly/bulk-memory-operations?

**Comment by lars-t-hansen** [comment]
Yes, I was thinking the same thing, we could usefully do that.

**Comment by binji** [comment]
Sounds good.

**Comment by binji** [comment]
Oh, I just updated this one, but it probably would be better to just remove this repo and use that one, right?

**Comment by jfbastien** [comment]
Fine by me, we should just circle back to the CG with this fact. I'm not sure when the next meeting will be yet given the conflict with TC39, will need to confirm with @flagxor before scheduling.

**Comment by binji** [comment]
OK, merged in this commit: https://github.com/WebAssembly/bulk-memory-operations/commit/dd356d5717bae3f304a0647fb0c7dc1461d3ccc9

**Comment by binji** [comment]
This was discussed in the [Jan 26th meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-01-26.md), and had unanimous consent. I'll follow up by removing the content from this repo and adding a link to bulk-memory-operations.
